let titles = [
	'',
	'Newborn',
	'Habit pawn',
	'Persistent ant',
	'Rising cadet',
	'Standard recruit',
	'Potential prospect',
	'Promising subject',
	'Blue belt',
	'Young acolyte',
	'Apprentice of the good ways',
	'Well applied enthusiast',
	'Doer',
	'Soldier of proficiency',
	'Well adjusted person',
	'Determined citizen',
	'Dependable Reference',
	'Hard working human',
	'Consistency Consultant',
	'Relentless Achiever',
	'Stubborn Accomplisher',
	'Visionary',
	'Future Builder',
	'Architect of Dreams',
	'Destiny Wrangler',
	'Habit Ninja',
	'Path Maker',
	'Growth PHD',
	'Established Luminary',
	'Agile Mountain',
	'Myth Archetype',
	'Legend Protagonist',
]

export default titles